import ZetaZero.HardyGaugeInvariantContourForm
import ZetaZero.RightEdgeArithmeticSource.SourceAlgebra
import ZetaZero.RightEdgeArithmeticSource.FiniteModelFubiniLift
import ZetaZero.RightEdgeArithmeticSource.CurvatureCoefficient
import ZetaZero.RightEdgeArithmeticSource.TranslatedPoleResidue
import ZetaZero.RightEdgeArithmeticSource.FreezingEstimate
import ZetaZero.RightEdgeArithmeticSource.StationaryPhaseGeometry
import ZetaZero.RightEdgeArithmeticSource.StationaryNormalization
import ZetaZero.RightEdgeArithmeticSource.NonstationaryPhaseBounds
import ZetaZero.RightEdgeArithmeticSource.StationaryQuadraticControl
import ZetaZero.RightEdgeArithmeticSource.StationaryLocalGeometry
import ZetaZero.RightEdgeArithmeticSource.StationaryGaussianScaling
import ZetaZero.RightEdgeArithmeticSource.StationaryOscillationControl
import ZetaZero.RightEdgeArithmeticSource.StationaryGaussianTail
import ZetaZero.RightEdgeArithmeticSource.StationaryFresnelAbel
import ZetaZero.RightEdgeArithmeticSource.StationaryMainTermError

/-!
# M04: Right-edge arithmetic source and dilation covariance

Stable facade for `sec:right-edge` and `sec:stationary`.  This node depends on
M02.
-/

namespace ZetaZero
namespace RightEdgeArithmeticSource

end RightEdgeArithmeticSource
end ZetaZero
